// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grid-layout': string;
  'grid-layout-container': string;
}
export const cssExports: CssExports;
export default cssExports;
