// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classic-layout': string;
  'classic-layout-content': string;
  'classic-layout-footer': string;
  'classic-layout-header': string;
  'classic-layout-hidden-left': string;
  'classic-layout-hidden-right': string;
  'classic-layout-left-sidebar': string;
  'classic-layout-main-body': string;
  'classic-layout-right-sidebar': string;
}
export const cssExports: CssExports;
export default cssExports;
